# Macro file for example B4
#
# beam settings
# To be run preferably in batch, without graphics:
# % exampleB4[a,b,c,d] run2.mac
#
#/run/numberOfWorkers 4
/run/initialize
#
# Default kinemtics found in PrimaryGeneratorAction
#
# this is expected to run over various energies E via runLoop.mac
/gun/particle e-
/gun/energy {E} GeV
#
/globalField/setValue 0 0 0 tesla
/run/printProgress 1000
/run/beamOn 20000

